// Generated by `npm run gen-types` (supabase gen types typescript --local)
// against the local Postgres instance — do not hand-edit. Regenerate after
// any migration change.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      ai_agent_runs: {
        Row: {
          agent_type: Database["public"]["Enums"]["agent_type"]
          created_at: string
          detail: string
          id: string
          input_ref: Json
          output: Json | null
          reviewed_at: string | null
          reviewed_by: string | null
          severity: Database["public"]["Enums"]["agent_run_severity"]
          status: Database["public"]["Enums"]["agent_run_status"]
          title: string
          trigger: string
        }
        Insert: {
          agent_type: Database["public"]["Enums"]["agent_type"]
          created_at?: string
          detail: string
          id?: string
          input_ref?: Json
          output?: Json | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          severity?: Database["public"]["Enums"]["agent_run_severity"]
          status?: Database["public"]["Enums"]["agent_run_status"]
          title: string
          trigger: string
        }
        Update: {
          agent_type?: Database["public"]["Enums"]["agent_type"]
          created_at?: string
          detail?: string
          id?: string
          input_ref?: Json
          output?: Json | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          severity?: Database["public"]["Enums"]["agent_run_severity"]
          status?: Database["public"]["Enums"]["agent_run_status"]
          title?: string
          trigger?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_agent_runs_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          after: Json | null
          before: Json | null
          created_at: string
          entity_id: string
          entity_table: string
          id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          entity_id: string
          entity_table: string
          id?: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          entity_id?: string
          entity_table?: string
          id?: string
        }
        Relationships: []
      }
      cargo_items: {
        Row: {
          category: Database["public"]["Enums"]["cargo_category"]
          created_at: string
          created_by: string | null
          id: string
          name: string
          purchase_order_id: string
          quantity: number
          received_at: string | null
          received_by: string | null
          received_quantity: number | null
          shipment_id: string | null
          unit: string
          updated_at: string
          volume_m3: number | null
          weight_kg: number | null
        }
        Insert: {
          category: Database["public"]["Enums"]["cargo_category"]
          created_at?: string
          created_by?: string | null
          id?: string
          name: string
          purchase_order_id: string
          quantity: number
          received_at?: string | null
          received_by?: string | null
          received_quantity?: number | null
          shipment_id?: string | null
          unit: string
          updated_at?: string
          volume_m3?: number | null
          weight_kg?: number | null
        }
        Update: {
          category?: Database["public"]["Enums"]["cargo_category"]
          created_at?: string
          created_by?: string | null
          id?: string
          name?: string
          purchase_order_id?: string
          quantity?: number
          received_at?: string | null
          received_by?: string | null
          received_quantity?: number | null
          shipment_id?: string | null
          unit?: string
          updated_at?: string
          volume_m3?: number | null
          weight_kg?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "cargo_items_purchase_order_id_fkey"
            columns: ["purchase_order_id"]
            isOneToOne: false
            referencedRelation: "purchase_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cargo_items_received_by_fkey"
            columns: ["received_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cargo_items_shipment_id_fkey"
            columns: ["shipment_id"]
            isOneToOne: false
            referencedRelation: "shipments"
            referencedColumns: ["id"]
          },
        ]
      }
      checkins: {
        Row: {
          checkin_at: string
          created_at: string
          hazard_zone_id: string | null
          id: string
          is_sos: boolean
          location: unknown
          notes: string | null
          personnel_id: string
          recorded_offline: boolean
        }
        Insert: {
          checkin_at?: string
          created_at?: string
          hazard_zone_id?: string | null
          id?: string
          is_sos?: boolean
          location?: unknown
          notes?: string | null
          personnel_id: string
          recorded_offline?: boolean
        }
        Update: {
          checkin_at?: string
          created_at?: string
          hazard_zone_id?: string | null
          id?: string
          is_sos?: boolean
          location?: unknown
          notes?: string | null
          personnel_id?: string
          recorded_offline?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "checkins_hazard_zone_id_fkey"
            columns: ["hazard_zone_id"]
            isOneToOne: false
            referencedRelation: "hazard_zones"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checkins_personnel_id_fkey"
            columns: ["personnel_id"]
            isOneToOne: false
            referencedRelation: "personnel"
            referencedColumns: ["id"]
          },
        ]
      }
      compliance_documents: {
        Row: {
          created_at: string
          document_type: Database["public"]["Enums"]["document_type"]
          file_name: string
          id: string
          purchase_order_id: string | null
          storage_path: string
          uploaded_by: string
          vendor_id: string
        }
        Insert: {
          created_at?: string
          document_type: Database["public"]["Enums"]["document_type"]
          file_name: string
          id?: string
          purchase_order_id?: string | null
          storage_path: string
          uploaded_by: string
          vendor_id: string
        }
        Update: {
          created_at?: string
          document_type?: Database["public"]["Enums"]["document_type"]
          file_name?: string
          id?: string
          purchase_order_id?: string | null
          storage_path?: string
          uploaded_by?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "compliance_documents_purchase_order_id_fkey"
            columns: ["purchase_order_id"]
            isOneToOne: false
            referencedRelation: "purchase_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "compliance_documents_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "compliance_documents_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      consumption_logs: {
        Row: {
          id: string
          inventory_id: string
          logged_at: string
          logged_by: string
          quantity_used: number
          recorded_offline: boolean
        }
        Insert: {
          id?: string
          inventory_id: string
          logged_at?: string
          logged_by: string
          quantity_used: number
          recorded_offline?: boolean
        }
        Update: {
          id?: string
          inventory_id?: string
          logged_at?: string
          logged_by?: string
          quantity_used?: number
          recorded_offline?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "consumption_logs_inventory_id_fkey"
            columns: ["inventory_id"]
            isOneToOne: false
            referencedRelation: "inventory"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consumption_logs_logged_by_fkey"
            columns: ["logged_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      expedition_stations: {
        Row: {
          expedition_id: string
          station_id: string
        }
        Insert: {
          expedition_id: string
          station_id: string
        }
        Update: {
          expedition_id?: string
          station_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "expedition_stations_expedition_id_fkey"
            columns: ["expedition_id"]
            isOneToOne: false
            referencedRelation: "expeditions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "expedition_stations_station_id_fkey"
            columns: ["station_id"]
            isOneToOne: false
            referencedRelation: "stations"
            referencedColumns: ["id"]
          },
        ]
      }
      expeditions: {
        Row: {
          code: string
          created_at: string
          created_by: string | null
          id: string
          name: string
          organization_id: string
          season_label: string
          status: Database["public"]["Enums"]["expedition_status"]
          updated_at: string
          vessel: string | null
          window_close: string
          window_open: string
        }
        Insert: {
          code: string
          created_at?: string
          created_by?: string | null
          id?: string
          name: string
          organization_id: string
          season_label: string
          status?: Database["public"]["Enums"]["expedition_status"]
          updated_at?: string
          vessel?: string | null
          window_close: string
          window_open: string
        }
        Update: {
          code?: string
          created_at?: string
          created_by?: string | null
          id?: string
          name?: string
          organization_id?: string
          season_label?: string
          status?: Database["public"]["Enums"]["expedition_status"]
          updated_at?: string
          vessel?: string | null
          window_close?: string
          window_open?: string
        }
        Relationships: [
          {
            foreignKeyName: "expeditions_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      hazard_zones: {
        Row: {
          created_at: string
          created_by: string | null
          geometry: unknown
          id: string
          name: string
          risk_notes: string | null
          station_id: string
          type: Database["public"]["Enums"]["hazard_type"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          geometry: unknown
          id?: string
          name: string
          risk_notes?: string | null
          station_id: string
          type: Database["public"]["Enums"]["hazard_type"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          geometry?: unknown
          id?: string
          name?: string
          risk_notes?: string | null
          station_id?: string
          type?: Database["public"]["Enums"]["hazard_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "hazard_zones_station_id_fkey"
            columns: ["station_id"]
            isOneToOne: false
            referencedRelation: "stations"
            referencedColumns: ["id"]
          },
        ]
      }
      incidents: {
        Row: {
          created_at: string
          created_by: string | null
          description: string | null
          expedition_id: string | null
          id: string
          raised_by_agent_run_id: string | null
          reported_by: string
          severity: Database["public"]["Enums"]["incident_severity"]
          station_id: string
          status: Database["public"]["Enums"]["incident_status"]
          timeline: Json
          title: string
          type: Database["public"]["Enums"]["incident_type"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          expedition_id?: string | null
          id?: string
          raised_by_agent_run_id?: string | null
          reported_by: string
          severity: Database["public"]["Enums"]["incident_severity"]
          station_id: string
          status?: Database["public"]["Enums"]["incident_status"]
          timeline?: Json
          title: string
          type: Database["public"]["Enums"]["incident_type"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          expedition_id?: string | null
          id?: string
          raised_by_agent_run_id?: string | null
          reported_by?: string
          severity?: Database["public"]["Enums"]["incident_severity"]
          station_id?: string
          status?: Database["public"]["Enums"]["incident_status"]
          timeline?: Json
          title?: string
          type?: Database["public"]["Enums"]["incident_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "incidents_expedition_id_fkey"
            columns: ["expedition_id"]
            isOneToOne: false
            referencedRelation: "expeditions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incidents_reported_by_fkey"
            columns: ["reported_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "incidents_station_id_fkey"
            columns: ["station_id"]
            isOneToOne: false
            referencedRelation: "stations"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory: {
        Row: {
          category: Database["public"]["Enums"]["cargo_category"]
          consumption_rate_per_day: number
          created_at: string
          created_by: string | null
          id: string
          name: string
          quantity: number
          reorder_threshold_days: number
          station_id: string
          unit: string
          updated_at: string
        }
        Insert: {
          category: Database["public"]["Enums"]["cargo_category"]
          consumption_rate_per_day?: number
          created_at?: string
          created_by?: string | null
          id?: string
          name: string
          quantity?: number
          reorder_threshold_days?: number
          station_id: string
          unit: string
          updated_at?: string
        }
        Update: {
          category?: Database["public"]["Enums"]["cargo_category"]
          consumption_rate_per_day?: number
          created_at?: string
          created_by?: string | null
          id?: string
          name?: string
          quantity?: number
          reorder_threshold_days?: number
          station_id?: string
          unit?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_station_id_fkey"
            columns: ["station_id"]
            isOneToOne: false
            referencedRelation: "stations"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          created_at: string
          id: string
          name: string
          type: Database["public"]["Enums"]["org_type"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          type: Database["public"]["Enums"]["org_type"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          type?: Database["public"]["Enums"]["org_type"]
          updated_at?: string
        }
        Relationships: []
      }
      personnel: {
        Row: {
          batch_label: string | null
          created_at: string
          created_by: string | null
          expedition_id: string
          id: string
          quarantine_status: Database["public"]["Enums"]["quarantine_status"]
          role_title: string
          station_id: string
          training_status: Database["public"]["Enums"]["training_status"]
          updated_at: string
          user_id: string
        }
        Insert: {
          batch_label?: string | null
          created_at?: string
          created_by?: string | null
          expedition_id: string
          id?: string
          quarantine_status?: Database["public"]["Enums"]["quarantine_status"]
          role_title: string
          station_id: string
          training_status?: Database["public"]["Enums"]["training_status"]
          updated_at?: string
          user_id: string
        }
        Update: {
          batch_label?: string | null
          created_at?: string
          created_by?: string | null
          expedition_id?: string
          id?: string
          quarantine_status?: Database["public"]["Enums"]["quarantine_status"]
          role_title?: string
          station_id?: string
          training_status?: Database["public"]["Enums"]["training_status"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "personnel_expedition_id_fkey"
            columns: ["expedition_id"]
            isOneToOne: false
            referencedRelation: "expeditions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "personnel_station_id_fkey"
            columns: ["station_id"]
            isOneToOne: false
            referencedRelation: "stations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "personnel_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          full_name: string
          id: string
          organization_id: string
          role: Database["public"]["Enums"]["user_role"]
          station_id: string | null
          updated_at: string
          vendor_id: string | null
        }
        Insert: {
          created_at?: string
          full_name: string
          id: string
          organization_id: string
          role: Database["public"]["Enums"]["user_role"]
          station_id?: string | null
          updated_at?: string
          vendor_id?: string | null
        }
        Update: {
          created_at?: string
          full_name?: string
          id?: string
          organization_id?: string
          role?: Database["public"]["Enums"]["user_role"]
          station_id?: string | null
          updated_at?: string
          vendor_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_station_id_fkey"
            columns: ["station_id"]
            isOneToOne: false
            referencedRelation: "stations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_orders: {
        Row: {
          committed_delivery_date: string | null
          created_at: string
          created_by: string | null
          id: string
          items_summary: string
          packing_deadline: string
          requisition_id: string
          status: Database["public"]["Enums"]["po_status"]
          updated_at: string
          vendor_id: string
        }
        Insert: {
          committed_delivery_date?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          items_summary: string
          packing_deadline: string
          requisition_id: string
          status?: Database["public"]["Enums"]["po_status"]
          updated_at?: string
          vendor_id: string
        }
        Update: {
          committed_delivery_date?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          items_summary?: string
          packing_deadline?: string
          requisition_id?: string
          status?: Database["public"]["Enums"]["po_status"]
          updated_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "purchase_orders_requisition_id_fkey"
            columns: ["requisition_id"]
            isOneToOne: false
            referencedRelation: "purchase_requisitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_orders_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_requisitions: {
        Row: {
          created_at: string
          created_by: string | null
          drafted_by_agent_run_id: string | null
          expedition_id: string
          id: string
          items: Json
          packing_deadline: string
          requested_by: string
          station_id: string
          status: Database["public"]["Enums"]["requisition_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          drafted_by_agent_run_id?: string | null
          expedition_id: string
          id?: string
          items?: Json
          packing_deadline: string
          requested_by: string
          station_id: string
          status?: Database["public"]["Enums"]["requisition_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          drafted_by_agent_run_id?: string | null
          expedition_id?: string
          id?: string
          items?: Json
          packing_deadline?: string
          requested_by?: string
          station_id?: string
          status?: Database["public"]["Enums"]["requisition_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "purchase_requisitions_expedition_id_fkey"
            columns: ["expedition_id"]
            isOneToOne: false
            referencedRelation: "expeditions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_requisitions_requested_by_fkey"
            columns: ["requested_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_requisitions_station_id_fkey"
            columns: ["station_id"]
            isOneToOne: false
            referencedRelation: "stations"
            referencedColumns: ["id"]
          },
        ]
      }
      report_embeddings: {
        Row: {
          content: string
          created_at: string
          embedding: string | null
          id: string
          source_id: string
          source_table: string
        }
        Insert: {
          content: string
          created_at?: string
          embedding?: string | null
          id?: string
          source_id: string
          source_table: string
        }
        Update: {
          content?: string
          created_at?: string
          embedding?: string | null
          id?: string
          source_id?: string
          source_table?: string
        }
        Relationships: []
      }
      shipments: {
        Row: {
          created_at: string
          created_by: string | null
          current_leg: string | null
          current_position: unknown
          destination_station_id: string
          eta: string | null
          expedition_id: string
          id: string
          mode: Database["public"]["Enums"]["shipment_mode"]
          progress_pct: number
          route: string
          status: Database["public"]["Enums"]["shipment_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          current_leg?: string | null
          current_position?: unknown
          destination_station_id: string
          eta?: string | null
          expedition_id: string
          id?: string
          mode: Database["public"]["Enums"]["shipment_mode"]
          progress_pct?: number
          route: string
          status?: Database["public"]["Enums"]["shipment_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          current_leg?: string | null
          current_position?: unknown
          destination_station_id?: string
          eta?: string | null
          expedition_id?: string
          id?: string
          mode?: Database["public"]["Enums"]["shipment_mode"]
          progress_pct?: number
          route?: string
          status?: Database["public"]["Enums"]["shipment_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "shipments_destination_station_id_fkey"
            columns: ["destination_station_id"]
            isOneToOne: false
            referencedRelation: "stations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shipments_expedition_id_fkey"
            columns: ["expedition_id"]
            isOneToOne: false
            referencedRelation: "expeditions"
            referencedColumns: ["id"]
          },
        ]
      }
      stations: {
        Row: {
          code: string
          coordinates: unknown
          created_at: string
          created_by: string | null
          id: string
          name: string
          organization_id: string
          personnel_capacity: number
          region: Database["public"]["Enums"]["station_region"]
          station_type: string
          updated_at: string
        }
        Insert: {
          code: string
          coordinates?: unknown
          created_at?: string
          created_by?: string | null
          id?: string
          name: string
          organization_id: string
          personnel_capacity?: number
          region: Database["public"]["Enums"]["station_region"]
          station_type: string
          updated_at?: string
        }
        Update: {
          code?: string
          coordinates?: unknown
          created_at?: string
          created_by?: string | null
          id?: string
          name?: string
          organization_id?: string
          personnel_capacity?: number
          region?: Database["public"]["Enums"]["station_region"]
          station_type?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "stations_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      travel_batch_members: {
        Row: {
          personnel_id: string
          travel_batch_id: string
        }
        Insert: {
          personnel_id: string
          travel_batch_id: string
        }
        Update: {
          personnel_id?: string
          travel_batch_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "travel_batch_members_personnel_id_fkey"
            columns: ["personnel_id"]
            isOneToOne: false
            referencedRelation: "personnel"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "travel_batch_members_travel_batch_id_fkey"
            columns: ["travel_batch_id"]
            isOneToOne: false
            referencedRelation: "travel_batches"
            referencedColumns: ["id"]
          },
        ]
      }
      travel_batches: {
        Row: {
          batch_code: string
          created_at: string
          created_by: string | null
          departure_date: string | null
          expedition_id: string
          id: string
          mode: Database["public"]["Enums"]["travel_mode"]
          transit_legs: Json
          updated_at: string
        }
        Insert: {
          batch_code: string
          created_at?: string
          created_by?: string | null
          departure_date?: string | null
          expedition_id: string
          id?: string
          mode: Database["public"]["Enums"]["travel_mode"]
          transit_legs?: Json
          updated_at?: string
        }
        Update: {
          batch_code?: string
          created_at?: string
          created_by?: string | null
          departure_date?: string | null
          expedition_id?: string
          id?: string
          mode?: Database["public"]["Enums"]["travel_mode"]
          transit_legs?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "travel_batches_expedition_id_fkey"
            columns: ["expedition_id"]
            isOneToOne: false
            referencedRelation: "expeditions"
            referencedColumns: ["id"]
          },
        ]
      }
      vendors: {
        Row: {
          category: string
          created_at: string
          created_by: string | null
          id: string
          location: string | null
          name: string
          organization_id: string
          performance_score: number
          updated_at: string
        }
        Insert: {
          category: string
          created_at?: string
          created_by?: string | null
          id?: string
          location?: string | null
          name: string
          organization_id: string
          performance_score?: number
          updated_at?: string
        }
        Update: {
          category?: string
          created_at?: string
          created_by?: string | null
          id?: string
          location?: string | null
          name?: string
          organization_id?: string
          performance_score?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendors_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      weather_snapshots: {
        Row: {
          created_at: string
          id: string
          raw_payload: Json | null
          risk_score: number
          shipment_id: string | null
          source: string
          station_id: string | null
          window_end: string
          window_start: string
        }
        Insert: {
          created_at?: string
          id?: string
          raw_payload?: Json | null
          risk_score: number
          shipment_id?: string | null
          source: string
          station_id?: string | null
          window_end: string
          window_start: string
        }
        Update: {
          created_at?: string
          id?: string
          raw_payload?: Json | null
          risk_score?: number
          shipment_id?: string | null
          source?: string
          station_id?: string | null
          window_end?: string
          window_start?: string
        }
        Relationships: [
          {
            foreignKeyName: "weather_snapshots_shipment_id_fkey"
            columns: ["shipment_id"]
            isOneToOne: false
            referencedRelation: "shipments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "weather_snapshots_station_id_fkey"
            columns: ["station_id"]
            isOneToOne: false
            referencedRelation: "stations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      current_org_id: { Args: never; Returns: string }
      current_role: {
        Args: never
        Returns: Database["public"]["Enums"]["user_role"]
      }
      current_station_id: { Args: never; Returns: string }
      current_vendor_id: { Args: never; Returns: string }
      is_command_staff: { Args: never; Returns: boolean }
      is_leadership_or_command_staff: { Args: never; Returns: boolean }
    }
    Enums: {
      agent_run_severity: "info" | "watch" | "critical"
      agent_run_status: "pending_review" | "approved" | "dismissed"
      agent_type:
        | "reorder_forecaster"
        | "vendor_deadline_watcher"
        | "weather_contingency_planner"
        | "cargo_reconciliation"
        | "safety_escalation"
        | "report_drafter"
        | "command_copilot"
      cargo_category: "fuel" | "food" | "medical" | "spares" | "instruments"
      document_type: "customs" | "msds" | "quality_cert" | "other"
      expedition_status: "planning" | "active" | "transit" | "closed"
      hazard_type: "crevasse" | "wildlife" | "whiteout-risk"
      incident_severity: "low" | "medium" | "high" | "critical"
      incident_status: "open" | "investigating" | "resolved"
      incident_type: "safety" | "medical" | "logistics"
      org_type: "ncpor" | "ministry" | "vendor"
      po_status:
        | "draft"
        | "sent"
        | "acknowledged"
        | "on-track"
        | "at-risk"
        | "late"
        | "delivered"
        | "cancelled"
      quarantine_status: "cleared" | "in-progress" | "not-required"
      requisition_status:
        | "draft"
        | "submitted"
        | "approved"
        | "converted_to_po"
        | "rejected"
      shipment_mode: "sea_vessel" | "air_charter" | "helicopter"
      shipment_status: "scheduled" | "in-transit" | "arrived" | "delayed"
      station_region: "antarctica" | "arctic"
      training_status: "complete" | "in-progress" | "overdue"
      travel_mode: "sea" | "air"
      user_role: "admin" | "ops" | "field" | "vendor" | "leadership"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      agent_run_severity: ["info", "watch", "critical"],
      agent_run_status: ["pending_review", "approved", "dismissed"],
      agent_type: [
        "reorder_forecaster",
        "vendor_deadline_watcher",
        "weather_contingency_planner",
        "cargo_reconciliation",
        "safety_escalation",
        "report_drafter",
        "command_copilot",
      ],
      cargo_category: ["fuel", "food", "medical", "spares", "instruments"],
      document_type: ["customs", "msds", "quality_cert", "other"],
      expedition_status: ["planning", "active", "transit", "closed"],
      hazard_type: ["crevasse", "wildlife", "whiteout-risk"],
      incident_severity: ["low", "medium", "high", "critical"],
      incident_status: ["open", "investigating", "resolved"],
      incident_type: ["safety", "medical", "logistics"],
      org_type: ["ncpor", "ministry", "vendor"],
      po_status: [
        "draft",
        "sent",
        "acknowledged",
        "on-track",
        "at-risk",
        "late",
        "delivered",
        "cancelled",
      ],
      quarantine_status: ["cleared", "in-progress", "not-required"],
      requisition_status: [
        "draft",
        "submitted",
        "approved",
        "converted_to_po",
        "rejected",
      ],
      shipment_mode: ["sea_vessel", "air_charter", "helicopter"],
      shipment_status: ["scheduled", "in-transit", "arrived", "delayed"],
      station_region: ["antarctica", "arctic"],
      training_status: ["complete", "in-progress", "overdue"],
      travel_mode: ["sea", "air"],
      user_role: ["admin", "ops", "field", "vendor", "leadership"],
    },
  },
} as const

